### ISSUE TITLE
Пиши @ сокращай

### ISSUE THREAD

**Issue by grem11n** [devopsfactors/devopsfactors#3]
Как на счёт объединить пункты про CI и CD в один?

Также было бо круто ужать текст во всех пунктах, чтобы на выходе получилась шпаргалка, которую можно распечатать и повесить на стене, как в случае c Agile manifesto

**Comment by Mykolaichenko** [comment]
CI и CD это же совершенно разные концепции, которые описывают разные процессы. Получается, что объединить их нельзя( 

Про шпаргалку +1, в идеале будет как https://12factor.net/

На главной краткое описание, по клику - развернутое
