### ISSUE TITLE
Пунктуация и грамматика

### ISSUE THREAD

**Issue by fadeevab** [devopsfactors/devopsfactors#9]
"Желательно что б был один и тот же менеджер." => "Желательно, чтоб был один и тот же менеджер." ("чтобы", "чтоб" пишется слитно; перед "чтобы" всегда запятая).

"Коммуникация это основной фундамент..." => "Коммуникация - это основной фундамент...". (Перед "это" всегда ставится тирэ).

И так далее, нужно пробежаться по всему тексту.

**Comment by Mykolaichenko** [comment]
@fadeevab, @kshcherban Thanks! Could you please handle that and create PR to master branch?
